# Copyright (c) 2022, Sun Yat-sen Univeristy, inc.
# All rights reserved.

# @author: Jiahua Rao
# @license: BSD-3-Clause, For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
# @contact: jiahua.rao@gmail.com


model:
  name: gin
  model_type: default
  trained: "model_checkpoints/gin_ogbg-molhiv_best.pth"
  pretrained: ""
  
  num_layers: 5
  hidden_size: 256

  aggregation: mean

  dropout: 0.5

datasets:
  name: "ogbg-molhiv"
  task_type: "classification"
  split_type: "defined"
  metric_type: "auc"

  smiles_column: "smiles"
  target_columns: ["HIV_active"]

  dim_target: 1
  dim_features: 9
  max_num_nodes: 222
  dim_edge_features: 3

run:
  task: "property_prediction"
  device: "cuda"
  distributed: False
  evaluate_only: False
  type: "train_val_test"

  # optimization-specific
  optimizer: Adam
  lr_sched: "linear_warmup_step_lr"
  init_lr: 0.031613208291481724
  max_lr: 0.034941422863329935
  min_lr: 0.006922426308786771
  step_size: 20
  warmup_epochs: 20
  weight_decay: 0.001126722210751067
  num_epochs: 154

  batch_size: 508
  seed: 42

  num_workers: 4
  class_balance: False
