# Copyright (c) 2022, Sun Yat-sen Univeristy, inc.
# All rights reserved.

# @author: Jiahua Rao
# @license: BSD-3-Clause, For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
# @contact: jiahua.rao@gmail.com


model:
  arch: gin
  model_type: gin_default
  
  num_layers: 2
  hidden_size: 64

  train_eps: True
  aggregation: mean

  dropout: 0.2

datasets:
  name: "ogbg-molbbbp"
  task: "property_prediction"
  task_type: "Classification"
  split_type: "defined"
  metric_type: "auc"

  path: ""
  smiles_column: "smiles"
  target_columns: ["p_np"]

run:
  device: "cuda"
  distributed: False
  evaluate_only: False
  type: "train_val_test"

  # optimization-specific
  optimizer: Adam
  lr_sched: "linear_warmup_step_lr"
  init_lr: 0.0001
  max_lr: 0.001
  min_lr: 0.000001
  step_size: 10
  warmup_epochs: 2.0
  weight_decay: 0.1
  batch_size: 50
  num_epochs: 100

  seed: 42
  output_dir: "outputs/property_prediction/CMPNN"

  num_workers: 4
  class_balance: False
