# Copyright (c) 2022, Sun Yat-sen Univeristy, inc.
# All rights reserved.

# @author: Jiahua Rao
# @license: BSD-3-Clause, For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
# @contact: jiahua.rao@gmail.com


model:
  name: gin
  model_type: default

  num_layers: 4
  hidden_size: 256
  aggregation: mean

  dropout: 0.5

datasets:
  name: "ogbg-molbbbp"
  task: "property_prediction"
  task_type: "classification"
  split_type: "defined"
  metric_type: "auc"

  smiles_column: "smiles"
  target_columns: ["p_np"]

run:
  task: "property_prediction"
  device: "cuda"
  distributed: False
  evaluate_only: False
  type: "train_val_test"

  # optimization-specific
  optimizer: Adam
  lr_sched: "linear_warmup_step_lr"
  init_lr: 9.310900188401472e-06
  max_lr: 0.02018108791282571
  min_lr: 0.005368407531446403
  step_size: 9
  warmup_epochs: 4.0
  weight_decay: 0.07315485684513329
  num_epochs: 50

  batch_size: 45
  seed: 42

  num_workers: 4
  class_balance: False
