# Copyright (c) 2022, Sun Yat-sen Univeristy, inc.
# All rights reserved.

# @author: Jiahua Rao
# @license: BSD-3-Clause, For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
# @contact: jiahua.rao@gmail.com


model:
  arch: gin
  model_type: gin_default
  
  num_layers: 5
  hidden_size: 300

  aggregation: mean

  dropout: 0.5


datasets:
  name: "ogbg-molesol"
  task_type: "regression"
  split_type: "defined"
  metric_type: ["rmse"]
  scaler_targets: True

  storage:
    - ogbg_molesol/mapping/mol.csv.gz
  smiles_column: "smiles"
  target_columns: ['measured log solubility in mols per litre']
  num_tasks: 1


run:
  task: "property_prediction"
  device: "cuda"
  distributed: False
  evaluate_only: False
  type: "train_val_test"

  # optimization-specific
  optimizer: Adam
  lr_sched: "linear_warmup_step_lr"
  init_lr: 0.001
  max_lr: 0.001
  min_lr: 0.000001
  step_size: 10
  warmup_epochs: 2.0
  weight_decay: 0.1
  num_epochs: 200

  batch_size: 32
  seed: 42

  num_workers: 4
  class_balance: False