model:
  - VAE
device:
  - cuda
num_epochs:
  - 30
  - 50
batch_size:
  - 64
  - 128
dim_embedding:
  - 64
  - 128
  - 256
freeze_embeddings:
  - False
q_d_h:
  - 256
  - 128
q_n_layers:
  - 1
  - 2
q_dropout:
  - 0.5
  - 0.2
q_bidir:
  - False
d_z:
  - 128
  - 64
d_d_h:
  - 512
  - 256
d_n_layers:
  - 3
  - 2
d_dropout:
  - 0.0
  - 0.1
optimizer:
  - Adam
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
shuffle:
  - True
gradient_clipping:
  - null
scheduler:
  - null
learning_rate:
  - 0.0001
  - 0.00001
l2:
  - 0.
  - 0.1