model:
  - ECC
device:
  - cuda
batch_size:
  - 32
  - 64
learning_rate:
  - 0.1
  - 0.01
num_epochs:
  - 50
  - 100
  - 300
num_lrs:
  - 1
optimizer:
  - SGD
scheduler:
  -
    class: ECCLR
    args:
      gamma: 0.1
      step_size: 10
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
shuffle:
  - True
l2:
  - 0.
  - 0.1
dropout:
  - 0.05
  - 0.25
dropout_final:
  - 0.1
num_layers:
  - 1
  - 2
dim_embedding:
  - 32
  - 64
seed:
  - 2022