model:
  - GraphNet
device:
  - cuda
batch_size:
  - 32
  - 64
learning_rate:
  - 0.001
  - 0.01
l2:
  - 0.0
  - 0.1
num_epochs:
  - 20
  - 100
  - 300
optimizer:
  - Adam
scheduler:
  - null
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
shuffle:
  - True
dim_node_hidden:
  - 256
  - 64
dim_edge_hidden:
  - 32
  - 64
num_step_set2set:
  - 2
  - 4
num_layer_set2set:
  - 2
  - 3
num_layers:
  - 2
  - 4
aggregation_type:
  - mean
  - add
  - max
seed:
  - 2022