model:
  - DMPNN
device:
  - cuda
bias:
  - False
dim_embedding:
  - 256
  - 300
  - 512
depth:
  - 3
  - 4
dropout:
  - 0.0
  - 0.2
activation:
  - ReLU
atom_messages:
  - False
undirected:
  - False
ffn_hidden_size:
  - 256
  - 300
ffn_num_layers:
  - 2
  - 3
  - 4
features_only:
  - False
aggregation:
  - mean
aggregation_norm:
  - 64
  - 100
warmup_epochs:
  - 2.0
learning_rate:
  - 0.00001
  - 0.0001
  - 0.01
l2:
  - 0.0
  - 0.1
max_lr:
  - 0.0001
final_lr:
  - 0.00001
class_balance:
  - False
batch_size:
  - 50
  - 32
  - 64
atom_descriptors:
  - null
use_input_features:
  - False
shuffle:
  - True
optimizer:
  - Adam
early_stopper:
  - null
gradient_clipping:
  - null
num_epochs:
  - 10
  - 30
  - 100
scheduler:
  - null
seed:
  - 2022