model:
  - CMPNN
device:
  - cuda
batch_size:
  - 50
  - 64
learning_rate:
  - 0.001
  # - 0.00001
l2:
  - 0.1
dim_embedding:
  - 256
  # - 300
bias:
  - False
  # - True
depth:
  - 2
  - 4
dropout:
  - 0.1
  - 0.0
activation:
  - ReLU
undirected:
  - False
  - True
ffn_hidden_size:
  - 256
  # - 512
ffn_num_layers:
  - 2
  - 5
atom_messages:
  - False
no_cache:
  - False
optimizer:
  - Adam
scheduler:
  -
    class: NoamLR
    args:
      warmup_epochs: [2.0]
      step_size: 10
      max_lr: [0.001]
      init_lr: [0.0001]
      final_lr: [0.0001]

early_stopper:
  -
    class: Patience
    args:
      patience: 500
      use_loss: True
gradient_clipping:
  - null
num_epochs:
  - 100
  # - 300
num_lrs:
  - 1
features_only:
  - False
atom_descriptors:
  - null
use_input_features:
  - False
shuffle:
  - True
seed:
  - 2022
