
ogbg-molbbbp:
  name: "ogbg-molbbbp"
  task: "property_prediction"
  task_type: "classification"
  split_type: "defined"
  metric_type: "auc"

  storage:
    - ogbg_molbbbp/mapping/mol.csv.gz
  smiles_column: "smiles"
  target_columns: ["p_np"]
  num_tasks: 1
  dim_target: 1
  multiclass_num_classes: 1
  feature: full