
ogbg-molfreesolv:
  name: "ogbg-molfreesolv"
  task: "property_prediction"
  task_type: "regression"
  split_type: "defined"
  metric_type: "rmse"

  scaler_targets: True
  storage:
    - ogbg_molfreesolv/mapping/mol.csv.gz
  smiles_column: "smiles"
  target_columns: ['expt']
  num_tasks: 1
  dim_target: 1
  feature: full