
ogbg-molhiv:
  name: "ogbg-molhiv"
  task: "property_prediction"
  task_type: "classification"
  split_type: "defined"
  metric_type: "auc"

  storage:
    - 'ogbg_molhiv/mapping/mol.csv.gz'
  smiles_column: "smiles"
  target_columns: ["HIV_active"]
  num_tasks: 1
  multiclass_num_classes: 1
