
ogbg-molbace:
  name: "ogbg-molbace"
  task: "property_prediction"
  task_type: "classification"
  split_type: "defined"
  metric_type: "auc"

  storage:
    - ogbg_molbace/mapping/mol.csv.gz
  smiles_column: "smiles"
  target_columns: ["Class"]
  num_tasks: 1
  multiclass_num_classes: 1