
ogbg-molesol:
  name: "ogbg-molesol"
  task: "property_prediction"
  task_type: "regression"
  split_type: "defined"
  metric_type: "rmse"

  scaler_targets: True
  storage:
    - ogbg_molesol/mapping/mol.csv.gz
  smiles_column: "smiles"
  target_columns: ['measured log solubility in mols per litre']
  num_tasks: 1
  feature: full
