# Copyright (c) 2022, Sun Yat-sen Univeristy, inc.
# All rights reserved.

# @author: Jiahua Rao
# @license: BSD-3-Clause, For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
# @contact: jiahua.rao@gmail.com


datasets:
  ogbg-molbbbp:
    name: "ogbg-molbbbp"
    task_type: "Classification"
    split_type: "defined"
    metric_type: "auc"
    num_tasks: 1

    storage:
      - ogbg_molbbbp/mapping/mol.csv.gz
    smiles_column: "smiles"
    target_columns: ["p_np"]
    multiclass_num_classes: 1

  ogbg-molhiv:
    name: "ogbg-molhiv"
    task_type: "Classification"
    split_type: "defined"
    metric_type: "auc"

    storage:
      - 'ogbg-molhiv/ogbg_molhiv.csv'
    smiles_column: "smiles"
    target_columns: ["HIV_active"]
