# Copyright (c) 2022, Sun Yat-sen Univeristy, inc.
# All rights reserved.

# @author: Jiahua Rao
# @license: BSD-3-Clause, For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
# @contact: jiahua.rao@gmail.com


model:
  name: gat
  model_type: default

  num_layers: 2
  dim_embedding: 256
  head: 8
  dropout: 0.1
  aggregation: mean